# Generated by Django 5.0.3 on 2024-07-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('number_plates', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
            ],
        ),
    ]
